### ISSUE TITLE
Galaxy Project Extensions versus entire seperate project

### ISSUE THREAD

**Issue by ghost** [cognoma/cognoma#18]
I took a look at your project flowchart. Are you familiar with the Galaxy Project? Seems like it implements almost exactly this and has a pretty substantial buy in from various biology projects.

Galaxy allows users to upload samples, and run it through various scientific processes, then returns results which can be part of complicated pipelines etc.

Galaxy allows developers of scientific software (mostly bioinformatics related, but you can use it for ANY unix type software, even a spell checker!), to create a pattern for use on the web.

I've used galaxy in a professional environment, developing commands for it as well as using it at a lab I developed research tools at, Drexel's EESI a signal processing / bioinformatics lab.

https://usegalaxy.org/

**Comment by cgreene** [comment]
@mutantturkey I'm familiar with Galaxy, but I think it targets a different audience. It's generally used for complicated sequencing pipelines. It's pretty good at piping files through executables, but I haven't previously seen it used for this type of project. The instances of it that I've seen are also more targeted someone with peripheral familiarity with comp bio/bioinformatics tools, as opposed to our target audience here. Could you share examples of the most usable machine learning workflows that you've found with galaxy? I'd love to see if they could meet this use case.

**Comment by ghost** [comment]
I'm less familiar with machine learning than I'd like to be, but bioinformatics at it's core is data analysis. I don't have any concrete examples of machine learning with galaxy , but I have developed a few  tools for galaxy from my own 16s sequence projects.

I think that more of an extension to Galaxy, one that handles the relevant data types, has basic tools for the project could allow the project to avoid reinventing the wheel when it comes to storage, frontend, backend process management because those problems have been solved in Galaxy's implementation.

Galaxy is very flexible when it comes to tool implementation, and code wise is relatively easy to improve upon. The Galaxy group - from my experience has been very helpful and willing to include new work into their projects.

There are some more data mining targeted instances of galaxy, like this one below.
https://galaxy.cbio.mskcc.org/

**Comment by cgreene** [comment]
@mutantturkey After some poking around that instance, it looks like Galaxy solves a slightly different problem for a very different audience. I'd be happy to look at some examples with you though if you find places where the functionality & audience are very close to what we're doing.

**Comment by martenson** [comment]
@cgreene From my @galaxyproject dev perspective this symbiosis could work and prove beneficial - however I am no machine learning/cancer specialist so there might be obstacles I do not see. Luckily an expert for using Galaxy in cancer research settings is Jeremy Goecks @jgoecks (https://cbi.gwu.edu/jeremy-goecks). Jeremy would you please find some time to evaluate the possibilities here?

**Comment by leobiscassi** [comment]
Hi everyone,
some galaxy tools implements machine learning algorithms by scikit learn wrappers [1] and some ideas about machine learning can be find in this discussion [2]. I don't know if helps with this project purpose, but can be a begin discussion about this theme. Let me know if I can help in something! :)

[1] [https://github.com/bgruening/galaxytools/tree/master/tools/sklearn](https://github.com/bgruening/galaxytools/tree/master/tools/sklearn)
[2] [https://github.com/bgruening/galaxytools/issues/370](https://github.com/bgruening/galaxytools/issues/370)

Best regards.

**Comment by cgreene** [comment]
I am aware that galaxy can be used as a wrapper for ML analyses. As I understand it, galaxy is a workflow manager can be used wherever one could put a series of functions/scripts/executables together.

Galaxy seems to hit a very different target audience than our project. I'm happy that you are enthusiastic about the project and hope that you will use your expertise to pitch in where you can. If there are places that galaxy naturally fits, we would be happy for you to contribute your expertise to take advantage of them. Please let us know where you see these specific opportunities given the aims and scope of this project.

**Comment by martenson** [comment]
@cgreene to my understanding the specific opportunities to use Galaxy are in the following areas:
![cognoma_cognoma__putting_machine_learning_in_the_hands_of_cancer_biologists](https://cloud.githubusercontent.com/assets/1814954/16934583/8e04e2d0-4d25-11e6-89ed-2f394a64696d.png)
It would need bigger discussion(call) to pinpoint this precisely. 

And of course there is no problem in refusing this as you obviously know the scope better - I base my estimate mostly just on the Cognomathon document.

Just out of curiosity how would you describe the difference in between Galaxy and Cognoma audiences?

**Comment by gwaybio** [comment]
It looks like [galaxy](https://github.com/galaxyproject) is a nice one-stop shop for biologists to analyze large datasets. This intersects with one of our goals: **Putting machine learning in the hands of cancer biologists** (see our tagline!). 

It also appears that [Galaxy](https://usegalaxy.org/) is primarily focused on next gen DNA sequencing, highlighting tools like SAMtools, Bamtools, Picard, peak calling, etc. and serves as a [toolshed](https://toolshed.g2.bx.psu.edu/) offering a wide variety of options. [Cognoma](github.com/cognoma), on the other hand, focuses exclusively on pre-processed gene expression, mutation, and clinical data across cancer tissues. We intend to design a simplistic interface with a cancer biologist as our target user. Since we are focused on specific datasets, a big advantage of Cognoma will be subsetting data intelligently to provide the most insight for an end user to develop/test hypotheses and drive their own research forward.

It also appears that @mutantturkey, @martenson, and @leobiscassi would offer much experience to project cognoma, as they have either developed using galaxy or are authors on the 2016 update (published in [Nucleic Acids Research](http://nar.oxfordjournals.org/content/early/2016/05/02/nar.gkw343.long)). They almost certainly have dealt with issues we will ultimately face in our project! Going along with our second goal/value, **project cognoma is an open source, community based project**, we would love to have you on board and contributing! Whether the contribution is filing issues like this, generating/reviewing pull requests, or attending our [meetups](http://www.meetup.com/DataPhilly/events/232591931/?rv=cr1&_af=event&_af_eid=232591931&https=off), we welcome your input.

**Comment by bgruening** [comment]
Nice project! Just my opinion because we are developing a Machine Learning extension for Galaxy here: https://github.com/bgruening/galaxytools (e.g. https://github.com/bgruening/galaxytools/tree/master/tools/sklearn). Thanks @leobiscassi for mentioning this small project!

I don't think Galaxy has one target audience today. There are many different ones. Galaxy is a framework and you should treat it like that. Galaxy is used for astronomy, cheminformatics, literature-mining, metabolomics, Constructive Solid Geometry and so on ...

You can even replace the web-interface of Galaxy with something more suited for your needs like the refinery project has done. The important part is you don't need to take care of the framework, you just plug-in your tool (and if you like replace the webinterface).

We will use Galaxy for machine learning and cancer genomics and we don't see any clash between our target-users. 

As a side note: Project Jupyter is now integrated in Galaxy as well, so `target users` are nowadays also scripting people that would like to combine wofkflows with adhoc scripting - very nice for machine learning.

**Comment by cgreene** [comment]
@bgruening @martenson : We all agree that Galaxy is a flexible system and that it _could_ be used in place of essentially any framework. The Galaxy framework is much heavier weight than the django rest framework highlighted by @martenson. Many of the features of Galaxy's back end (flexiblity with data types, management of files through multi-executable workflows) are not relevant to this system.

While Galaxy provides a UI suitable for some projects, those benefits don't seem to accrue to us in this case. For example, we are not targeting individuals who would be aware of Jupyter, or even aiming to write python code. In terms of UI, Galaxy is a wonderful solution to a very different problem.

Fortunately, the cognoma system is set up with loosely coupled components. Where you see an easy drop-in replacement with Galaxy, we'd love to have you contribute that solution. I could easily see you contributing a galaxy-cognoma repository that provided a Galaxy solution. This would allow us to compare both solutions on their technical merits.

Thank you again for your input!

**Comment by cgreene** [comment]
The galaxy-dev mailing list has a discussion on this topic as well that was posted by @mutantturkey :
http://dev.list.galaxyproject.org/cognoma-td4669691.html

I attempted to reply but my comment is awaiting moderator approval:

> Thank you for your interest in the cognoma project [ http://dev.list.galaxyproject.org/cognoma-td4669691.html ]. As it turns out, we have heard of Galaxy. It would be hard to be in computational biology and unaware of Galaxy. We appreciate the galaxy project's contributions to web-based workflows in bioinformatics. For the use case and target audience that we aim to serve, galaxy seemed less suited than alternative light weight and modular approaches. 
> 
> Of course, we appreciate your enthusiasm for galaxy and cognoma! If you feel passionately that galaxy is the right framework, the easiest way to demonstrate that is by delivering a galaxy-cognoma solution.
> 
> Thanks!
> Casey

**Comment by martenson** [comment]
@cgreene Approved. You can now post freely to that list.

**Comment by dhimmel** [comment]
Can anyone point to any existing webapps using Galaxy? We're going for a highly customized and user-friendly interface.

> You can even replace the web-interface of Galaxy with something more suited for your needs like the refinery project has done.

What's the link to the refinery project?

**Comment by bgruening** [comment]
@dhimmel I think user-friendly is hard to define but here are two nice examples:
- http://www.refinery-platform.org
- http://rnaseq.pathogenportal.org

You will probably find many more on https://wiki.galaxyproject.org/PublicGalaxyServers
Moreover [Tripal](http://gmod.org/wiki/Tripal) is not really a interface for Galaxy but there is also a Galaxy plugin so that you can start certain jobs from Tripal.
The Galaxy API is quite powerful and has bindings for python, php, Java ....

**Comment by dhimmel** [comment]
I'm not convinced Galaxy is what we need. For now I'm going to close this issue. If individuals at our meetup or other Project Cognoma contributors would like to explore Galaxy, we'll support them and reopen this issue. Thanks everyone for the feedback.
