### ISSUE TITLE
Refining the webapp's scope: return analyses as Jupyter notebooks

### ISSUE THREAD

**Issue by dhimmel** [cognoma/cognoma#63]
Currently, we've made good progress on the query building portion of the frontend. You can play with it at http://cognoma.org/query-builder/mutations. Thanks @bdolly and Think Company for the hard work on the frontend. The backend is also close to supporting the necessary API calls for the query builder. Thanks @awm33, @dcgoss, @stephenshank, @kurtwheeler and others who have helped get the backend in place.

However, we are not far along with the results viewer. The machine-learning team has focused development efforts on Jupyter notebooks. Therefore one option is to return completed analyses in Jupyter notebooks rather than via a webapp results viewer. Here are the advantages:

1. **Enhanced reproducibility**: researchers will have access to the Python source code to perform their analysis.
2. **Enhanced customizability**: researchers can now add custom steps or outputs to the analysis. However, researchers who don't know Python, can still just use the query builder to generate an already executed notebook.
3. **Promotes data science**: we introduce users to Jupyter notebooks and the actual code behind the analyses, which is exciting from the perspective of making cancer biologists into data scientists.
4. **Focuses development**: this aligns the development needs more closely with the skills and interests of the contributor base. We will still have backend / frontend needs, but we will have a larger portion of the project that can be done by primarily DataPhilly contributors.

Under this proposal, the query builder would remain largely the same. But when a user submitted an analysis, a Jupyter template would be filled in based on the user's specification. The backend would then run the notebook and return the completed notebook to the user (along with a conda environment, so the user can run it on their own machine).

@gwaygenomics @cgreene and others: thoughts?

**Comment by bdolly** [comment]
@dhimmel I think the results viewer is still very much viable as part of the webapp and is laid out in the front-end roadmap for development. I think it would be helpful to focus on getting the webapp results viewer up and then incorporating the Jupyter notebook as a export feature. 

I am unable to make the meetup tonight (4/26) due to prior obligations. I plan on continuing development of the webapp in the future, my schedule recently has just not permitted much time to do. It would be greatly helpful if we could recruit another front-end dev or two to help with the lift as design, dev, and testing is alot to take on.

**Comment by cgreene** [comment]
I like the idea of returning analyses as Jupyter notebooks. This has a number of important benefits. One of the primary ones is that the mission of the project is to put TCGA data + ML methods into the hands of cancer biologists. By returning an iPython notebook that has already been run, the recipient can also take that notebook and alter key assumptions that we made (if warranted) to conduct their own analyses.

Since the workflow up to a potential notebook is identical to the workflow for the results viewer, this idea seems to be a major win. It also provides an incremental result that could be returned to users and can inform subsequent community development of a results viewer.

After considering these points, I'd say :+1:

**Comment by dhimmel** [comment]
@bdolly I think you make a good point that notebook export can coexist with a webapp results viewer. If we go ahead with the notebook idea, we'll make sure not to create any incompatibilities with a potential frontend results viewer.

The proposal can be boiled down to as having a notebook that executes the analysis. The notebook can import functions from [`cognoma/cognoml`](https://github.com/cognoma/cognoml) and [`cognoma/figshare`](https://github.com/cognoma/figshare). It will export data that can be stored in the backend and later passed to the frontend.

**Comment by wisygig** [comment]
I'm willing to look at this.

**Comment by dcgoss** [comment]
Is this issue solved at this point? @dhimmel

**Comment by dhimmel** [comment]
> Is this issue solved at this point?

Yep!
